spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password: 1234
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      #ddl-auto: none
      # 애플리케이션 구동할 때, drop 후 create
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  h2:
    console:
      enabled: true
      path: /h2-console

#logging:
 # level:
    #org.hibernate.SQL: debug
    #org.hibernate.type: trace
