spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password: 1234
    driverClassName: org.h2.Driver


  jpa:
    #hibernate:
      #ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
